; Auto-generated. Do not edit!


(cl:in-package part_fetcher-msg)


;//! \htmlinclude PartFetcherGoal.msg.html

(cl:defclass <PartFetcherGoal> (roslisp-msg-protocol:ros-message)
  ((object_id
    :reader object_id
    :initarg :object_id
    :type cl:integer
    :initform 0)
   (object_frame
    :reader object_frame
    :initarg :object_frame
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped))
   (desired_frame
    :reader desired_frame
    :initarg :desired_frame
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass PartFetcherGoal (<PartFetcherGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PartFetcherGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PartFetcherGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name part_fetcher-msg:<PartFetcherGoal> is deprecated: use part_fetcher-msg:PartFetcherGoal instead.")))

(cl:ensure-generic-function 'object_id-val :lambda-list '(m))
(cl:defmethod object_id-val ((m <PartFetcherGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader part_fetcher-msg:object_id-val is deprecated.  Use part_fetcher-msg:object_id instead.")
  (object_id m))

(cl:ensure-generic-function 'object_frame-val :lambda-list '(m))
(cl:defmethod object_frame-val ((m <PartFetcherGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader part_fetcher-msg:object_frame-val is deprecated.  Use part_fetcher-msg:object_frame instead.")
  (object_frame m))

(cl:ensure-generic-function 'desired_frame-val :lambda-list '(m))
(cl:defmethod desired_frame-val ((m <PartFetcherGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader part_fetcher-msg:desired_frame-val is deprecated.  Use part_fetcher-msg:desired_frame instead.")
  (desired_frame m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PartFetcherGoal>) ostream)
  "Serializes a message object of type '<PartFetcherGoal>"
  (cl:let* ((signed (cl:slot-value msg 'object_id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'object_frame) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'desired_frame) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PartFetcherGoal>) istream)
  "Deserializes a message object of type '<PartFetcherGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'object_id) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'object_frame) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'desired_frame) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PartFetcherGoal>)))
  "Returns string type for a message object of type '<PartFetcherGoal>"
  "part_fetcher/PartFetcherGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PartFetcherGoal)))
  "Returns string type for a message object of type 'PartFetcherGoal"
  "part_fetcher/PartFetcherGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PartFetcherGoal>)))
  "Returns md5sum for a message object of type '<PartFetcherGoal>"
  "3ed50a2a1765af4bdef88bc97e5adc74")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PartFetcherGoal)))
  "Returns md5sum for a message object of type 'PartFetcherGoal"
  "3ed50a2a1765af4bdef88bc97e5adc74")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PartFetcherGoal>)))
  "Returns full string definition for message of type '<PartFetcherGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#action message for part fetcher~%#specify a part ID, starting pose, and desired destination pose~%int32 object_id~%geometry_msgs/PoseStamped object_frame~%geometry_msgs/PoseStamped desired_frame~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PartFetcherGoal)))
  "Returns full string definition for message of type 'PartFetcherGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#action message for part fetcher~%#specify a part ID, starting pose, and desired destination pose~%int32 object_id~%geometry_msgs/PoseStamped object_frame~%geometry_msgs/PoseStamped desired_frame~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PartFetcherGoal>))
  (cl:+ 0
     4
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'object_frame))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'desired_frame))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PartFetcherGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PartFetcherGoal
    (cl:cons ':object_id (object_id msg))
    (cl:cons ':object_frame (object_frame msg))
    (cl:cons ':desired_frame (desired_frame msg))
))
