(cl:in-package object_grabber-msg)
(cl:export '(ACTION_CODE-VAL
          ACTION_CODE
          OBJECT_ID-VAL
          OBJECT_ID
          GRASP_OPTION-VAL
          GRASP_OPTION
          APPROACH_STRATEGY-VAL
          APPROACH_STRATEGY
          LIFT_OBJECT_STRATEGY-VAL
          LIFT_OBJECT_STRATEGY
          DROPOFF_STRATEGY-VAL
          DROPOFF_STRATEGY
          DROPOFF_WITHDRAW_STRATEGY-VAL
          DROPOFF_WITHDRAW_STRATEGY
          OBJECT_FRAME-VAL
          OBJECT_FRAME
          SPEED_FACTOR-VAL
          SPEED_FACTOR
          GRIPPER_TEST_PARAMS-VAL
          GRIPPER_TEST_PARAMS
))