; Auto-generated. Do not edit!


(cl:in-package arm7dof_traj_as-msg)


;//! \htmlinclude trajResult.msg.html

(cl:defclass <trajResult> (roslisp-msg-protocol:ros-message)
  ((return_val
    :reader return_val
    :initarg :return_val
    :type cl:integer
    :initform 0))
)

(cl:defclass trajResult (<trajResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <trajResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'trajResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm7dof_traj_as-msg:<trajResult> is deprecated: use arm7dof_traj_as-msg:trajResult instead.")))

(cl:ensure-generic-function 'return_val-val :lambda-list '(m))
(cl:defmethod return_val-val ((m <trajResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm7dof_traj_as-msg:return_val-val is deprecated.  Use arm7dof_traj_as-msg:return_val instead.")
  (return_val m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <trajResult>) ostream)
  "Serializes a message object of type '<trajResult>"
  (cl:let* ((signed (cl:slot-value msg 'return_val)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <trajResult>) istream)
  "Deserializes a message object of type '<trajResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'return_val) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<trajResult>)))
  "Returns string type for a message object of type '<trajResult>"
  "arm7dof_traj_as/trajResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'trajResult)))
  "Returns string type for a message object of type 'trajResult"
  "arm7dof_traj_as/trajResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<trajResult>)))
  "Returns md5sum for a message object of type '<trajResult>"
  "d272e5e4ccd8d235962127b04bb0773f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'trajResult)))
  "Returns md5sum for a message object of type 'trajResult"
  "d272e5e4ccd8d235962127b04bb0773f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<trajResult>)))
  "Returns full string definition for message of type '<trajResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%#return_val = 1 for traj complete; traj_id should echo the input traj_id~%int32 return_val~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'trajResult)))
  "Returns full string definition for message of type 'trajResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%#return_val = 1 for traj complete; traj_id should echo the input traj_id~%int32 return_val~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <trajResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <trajResult>))
  "Converts a ROS message object to a list"
  (cl:list 'trajResult
    (cl:cons ':return_val (return_val msg))
))
