set(object_manipulation_properties_MESSAGE_FILES "")
set(object_manipulation_properties_SERVICE_FILES "/home/abcaps35/ros_ws_nogit/src/learning_ros/Part_5/object_manipulation_properties/srv/objectManipulationQuery.srv")
