(cl:defpackage arm_motion_action-msg
  (:use )
  (:export
   "<ARM_INTERFACEACTION>"
   "ARM_INTERFACEACTION"
   "<ARM_INTERFACEACTIONFEEDBACK>"
   "ARM_INTERFACEACTIONFEEDBACK"
   "<ARM_INTERFACEACTIONGOAL>"
   "ARM_INTERFACEACTIONGOAL"
   "<ARM_INTERFACEACTIONRESULT>"
   "ARM_INTERFACEACTIONRESULT"
   "<ARM_INTERFACEFEEDBACK>"
   "ARM_INTERFACEFEEDBACK"
   "<ARM_INTERFACEGOAL>"
   "ARM_INTERFACEGOAL"
   "<ARM_INTERFACERESULT>"
   "ARM_INTERFACERESULT"
  ))

