(cl:defpackage generic_gripper_services-srv
  (:use )
  (:export
   "GENERICGRIPPERINTERFACE"
   "<GENERICGRIPPERINTERFACE-REQUEST>"
   "GENERICGRIPPERINTERFACE-REQUEST"
   "<GENERICGRIPPERINTERFACE-RESPONSE>"
   "GENERICGRIPPERINTERFACE-RESPONSE"
  ))

