(cl:defpackage navigator-msg
  (:use )
  (:export
   "<NAVIGATORACTION>"
   "NAVIGATORACTION"
   "<NAVIGATORACTIONFEEDBACK>"
   "NAVIGATORACTIONFEEDBACK"
   "<NAVIGATORACTIONGOAL>"
   "NAVIGATORACTIONGOAL"
   "<NAVIGATORACTIONRESULT>"
   "NAVIGATORACTIONRESULT"
   "<NAVIGATORFEEDBACK>"
   "NAVIGATORFEEDBACK"
   "<NAVIGATORGOAL>"
   "NAVIGATORGOAL"
   "<NAVIGATORRESULT>"
   "NAVIGATORRESULT"
  ))

