# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from object_grabber/object_grabber3Goal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class object_grabber3Goal(genpy.Message):
  _md5sum = "4bd60dc24cfaef34227a06571f5af012"
  _type = "object_grabber/object_grabber3Goal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#object_grabber action message
#pass in an object code and the object's frame (w/rt named frame_id)
#object_grabber will plan approach, grasp and lift of object
#returns codes regarding outcome

#action codes:
int32 TEST_CODE = 0   #a simple "ping" to action server
int32 MOVE_TO_WAITING_POSE = 1 #move to a pose, defined on param server, that is convenient
                               #e.g., prepared to approach a surface, but out of way of sensors
int32 PLAN_MOVE_TO_GRASP_POSE  =2   #expects parameters of current_object_pose, object_ID, grasp_option, approach_option
                               #must send separate "grasp" command to gripper
int32 PLAN_MOVE_FINE_TO_GRASP_POSE  =3   #as above, but finer/slower approach motion
int32 PLAN_MOVE_OBJECT_JSPACE =4    #move a grasped object to a destination pose using simple, joint-space move
                               #expects params: des_object_pose, object_ID, grasp_option (need to know how object is grasped)
int32 PLAN_MOVE_OBJECT_CSPACE = 5   #move a grasped object with Cartesian motion to a desired object pose
                               #params:  des_object_pose, object_ID, grasp_option
int32 PLAN_MOVE_FINE_OBJECT_CSPACE = 6 #as above, but w/ finer, slower motion

int32 PLAN_WITHDRAW_FROM_OBJECT = 7 #with object grasp released, perform departure from object using specified depart strategy
                               #params: object_ID, grasp_option, depart_option
int32 PLAN_WITHDRAW_FINE_FROM_OBJECT = 8 #as above, but slower/more precise motion

int32 PLAN_OBJECT_GRASP = 9  #combine multiple elements above to acquire an object

int32 GRAB_OBJECT = 101 #plan and attempt to execute object acquisition, including grasp and lift
int32 DROPOFF_OBJECT = 102 #plan and attempt to execute object placement and arm withdrawal

int32 SET_SPEED_FACTOR = 10    #use arg speed_factor to change time scale of trajectory plan; larger than 1.0--> slower

#manipulation strategy options:
int32 DEFAULT_GRASP_STRATEGY = 0
#has corresponding default approach and depart strategies

int32 EXECUTE_PLANNED_MOVE = 100 #accept arm-motion plan and enable its execution

#generalized gripper commands:
int32 GRIPPER_PREPARE_GRASP_OBJECT = 20 #may require gripper to prepare for grasp approach, e.g. open fingers
int32 GRIPPER_GRASP_OBJECT = 21        #command to perform appropriate action to grasp object, 
                               #assumes gripper is in appropriate pose, prepared to grasp object
                               #client does not need to know what type of gripper is used
int32 GRIPPER_RELEASE_OBJECT = 22      #command to gripper to release a grasped object
                               #params: object ID and grasp option used; 
int32 GRIPPER_IS_OBJECT_GRASPED = 23   #a query; may require object_ID, grasp option used, and/or corresponding grasp test parameters; 
                               #should return true/false

#goal:
int32 action_code
int32 object_id
int32 grasp_option
int32 approach_strategy
int32 lift_object_strategy
int32 dropoff_strategy
int32 dropoff_withdraw_strategy
geometry_msgs/PoseStamped object_frame  #should be w/rt system_ref_frame, or have tf to this frame available
float64 speed_factor #default to 1.0
float64[] gripper_test_params

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  # Pseudo-constants
  TEST_CODE = 0
  MOVE_TO_WAITING_POSE = 1
  PLAN_MOVE_TO_GRASP_POSE = 2
  PLAN_MOVE_FINE_TO_GRASP_POSE = 3
  PLAN_MOVE_OBJECT_JSPACE = 4
  PLAN_MOVE_OBJECT_CSPACE = 5
  PLAN_MOVE_FINE_OBJECT_CSPACE = 6
  PLAN_WITHDRAW_FROM_OBJECT = 7
  PLAN_WITHDRAW_FINE_FROM_OBJECT = 8
  PLAN_OBJECT_GRASP = 9
  GRAB_OBJECT = 101
  DROPOFF_OBJECT = 102
  SET_SPEED_FACTOR = 10
  DEFAULT_GRASP_STRATEGY = 0
  EXECUTE_PLANNED_MOVE = 100
  GRIPPER_PREPARE_GRASP_OBJECT = 20
  GRIPPER_GRASP_OBJECT = 21
  GRIPPER_RELEASE_OBJECT = 22
  GRIPPER_IS_OBJECT_GRASPED = 23

  __slots__ = ['action_code','object_id','grasp_option','approach_strategy','lift_object_strategy','dropoff_strategy','dropoff_withdraw_strategy','object_frame','speed_factor','gripper_test_params']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','geometry_msgs/PoseStamped','float64','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       action_code,object_id,grasp_option,approach_strategy,lift_object_strategy,dropoff_strategy,dropoff_withdraw_strategy,object_frame,speed_factor,gripper_test_params

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(object_grabber3Goal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.action_code is None:
        self.action_code = 0
      if self.object_id is None:
        self.object_id = 0
      if self.grasp_option is None:
        self.grasp_option = 0
      if self.approach_strategy is None:
        self.approach_strategy = 0
      if self.lift_object_strategy is None:
        self.lift_object_strategy = 0
      if self.dropoff_strategy is None:
        self.dropoff_strategy = 0
      if self.dropoff_withdraw_strategy is None:
        self.dropoff_withdraw_strategy = 0
      if self.object_frame is None:
        self.object_frame = geometry_msgs.msg.PoseStamped()
      if self.speed_factor is None:
        self.speed_factor = 0.
      if self.gripper_test_params is None:
        self.gripper_test_params = []
    else:
      self.action_code = 0
      self.object_id = 0
      self.grasp_option = 0
      self.approach_strategy = 0
      self.lift_object_strategy = 0
      self.dropoff_strategy = 0
      self.dropoff_withdraw_strategy = 0
      self.object_frame = geometry_msgs.msg.PoseStamped()
      self.speed_factor = 0.
      self.gripper_test_params = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7i3I().pack(_x.action_code, _x.object_id, _x.grasp_option, _x.approach_strategy, _x.lift_object_strategy, _x.dropoff_strategy, _x.dropoff_withdraw_strategy, _x.object_frame.header.seq, _x.object_frame.header.stamp.secs, _x.object_frame.header.stamp.nsecs))
      _x = self.object_frame.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8d().pack(_x.object_frame.pose.position.x, _x.object_frame.pose.position.y, _x.object_frame.pose.position.z, _x.object_frame.pose.orientation.x, _x.object_frame.pose.orientation.y, _x.object_frame.pose.orientation.z, _x.object_frame.pose.orientation.w, _x.speed_factor))
      length = len(self.gripper_test_params)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.gripper_test_params))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.object_frame is None:
        self.object_frame = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.action_code, _x.object_id, _x.grasp_option, _x.approach_strategy, _x.lift_object_strategy, _x.dropoff_strategy, _x.dropoff_withdraw_strategy, _x.object_frame.header.seq, _x.object_frame.header.stamp.secs, _x.object_frame.header.stamp.nsecs,) = _get_struct_7i3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_frame.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_frame.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.object_frame.pose.position.x, _x.object_frame.pose.position.y, _x.object_frame.pose.position.z, _x.object_frame.pose.orientation.x, _x.object_frame.pose.orientation.y, _x.object_frame.pose.orientation.z, _x.object_frame.pose.orientation.w, _x.speed_factor,) = _get_struct_8d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.gripper_test_params = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7i3I().pack(_x.action_code, _x.object_id, _x.grasp_option, _x.approach_strategy, _x.lift_object_strategy, _x.dropoff_strategy, _x.dropoff_withdraw_strategy, _x.object_frame.header.seq, _x.object_frame.header.stamp.secs, _x.object_frame.header.stamp.nsecs))
      _x = self.object_frame.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8d().pack(_x.object_frame.pose.position.x, _x.object_frame.pose.position.y, _x.object_frame.pose.position.z, _x.object_frame.pose.orientation.x, _x.object_frame.pose.orientation.y, _x.object_frame.pose.orientation.z, _x.object_frame.pose.orientation.w, _x.speed_factor))
      length = len(self.gripper_test_params)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.gripper_test_params.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.object_frame is None:
        self.object_frame = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.action_code, _x.object_id, _x.grasp_option, _x.approach_strategy, _x.lift_object_strategy, _x.dropoff_strategy, _x.dropoff_withdraw_strategy, _x.object_frame.header.seq, _x.object_frame.header.stamp.secs, _x.object_frame.header.stamp.nsecs,) = _get_struct_7i3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_frame.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_frame.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.object_frame.pose.position.x, _x.object_frame.pose.position.y, _x.object_frame.pose.position.z, _x.object_frame.pose.orientation.x, _x.object_frame.pose.orientation.y, _x.object_frame.pose.orientation.z, _x.object_frame.pose.orientation.w, _x.speed_factor,) = _get_struct_8d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.gripper_test_params = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7i3I = None
def _get_struct_7i3I():
    global _struct_7i3I
    if _struct_7i3I is None:
        _struct_7i3I = struct.Struct("<7i3I")
    return _struct_7i3I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
