// Generated by gencpp from file example_interactive_marker/ImNodeSvcMsgResponse.msg
// DO NOT EDIT!


#ifndef EXAMPLE_INTERACTIVE_MARKER_MESSAGE_IMNODESVCMSGRESPONSE_H
#define EXAMPLE_INTERACTIVE_MARKER_MESSAGE_IMNODESVCMSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace example_interactive_marker
{
template <class ContainerAllocator>
struct ImNodeSvcMsgResponse_
{
  typedef ImNodeSvcMsgResponse_<ContainerAllocator> Type;

  ImNodeSvcMsgResponse_()
    : poseStamped_IM_current()  {
    }
  ImNodeSvcMsgResponse_(const ContainerAllocator& _alloc)
    : poseStamped_IM_current(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _poseStamped_IM_current_type;
  _poseStamped_IM_current_type poseStamped_IM_current;





  typedef boost::shared_ptr< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ImNodeSvcMsgResponse_

typedef ::example_interactive_marker::ImNodeSvcMsgResponse_<std::allocator<void> > ImNodeSvcMsgResponse;

typedef boost::shared_ptr< ::example_interactive_marker::ImNodeSvcMsgResponse > ImNodeSvcMsgResponsePtr;
typedef boost::shared_ptr< ::example_interactive_marker::ImNodeSvcMsgResponse const> ImNodeSvcMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator1> & lhs, const ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.poseStamped_IM_current == rhs.poseStamped_IM_current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator1> & lhs, const ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace example_interactive_marker

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbedb23e0aaabca1697bafa8180aafdc";
  }

  static const char* value(const ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbedb23e0aaabca1ULL;
  static const uint64_t static_value2 = 0x697bafa8180aafdcULL;
};

template<class ContainerAllocator>
struct DataType< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "example_interactive_marker/ImNodeSvcMsgResponse";
  }

  static const char* value(const ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#return the IM pose\n"
"geometry_msgs/PoseStamped poseStamped_IM_current\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poseStamped_IM_current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImNodeSvcMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::example_interactive_marker::ImNodeSvcMsgResponse_<ContainerAllocator>& v)
  {
    s << indent << "poseStamped_IM_current: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.poseStamped_IM_current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAMPLE_INTERACTIVE_MARKER_MESSAGE_IMNODESVCMSGRESPONSE_H
