// Auto-generated. Do not edit!

// (in-package part_fetcher.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class PartFetcherGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.object_id = null;
      this.object_frame = null;
      this.desired_frame = null;
    }
    else {
      if (initObj.hasOwnProperty('object_id')) {
        this.object_id = initObj.object_id
      }
      else {
        this.object_id = 0;
      }
      if (initObj.hasOwnProperty('object_frame')) {
        this.object_frame = initObj.object_frame
      }
      else {
        this.object_frame = new geometry_msgs.msg.PoseStamped();
      }
      if (initObj.hasOwnProperty('desired_frame')) {
        this.desired_frame = initObj.desired_frame
      }
      else {
        this.desired_frame = new geometry_msgs.msg.PoseStamped();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PartFetcherGoal
    // Serialize message field [object_id]
    bufferOffset = _serializer.int32(obj.object_id, buffer, bufferOffset);
    // Serialize message field [object_frame]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.object_frame, buffer, bufferOffset);
    // Serialize message field [desired_frame]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.desired_frame, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PartFetcherGoal
    let len;
    let data = new PartFetcherGoal(null);
    // Deserialize message field [object_id]
    data.object_id = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [object_frame]
    data.object_frame = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    // Deserialize message field [desired_frame]
    data.desired_frame = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.object_frame);
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.desired_frame);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'part_fetcher/PartFetcherGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3ed50a2a1765af4bdef88bc97e5adc74';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #action message for part fetcher
    #specify a part ID, starting pose, and desired destination pose
    int32 object_id
    geometry_msgs/PoseStamped object_frame
    geometry_msgs/PoseStamped desired_frame
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PartFetcherGoal(null);
    if (msg.object_id !== undefined) {
      resolved.object_id = msg.object_id;
    }
    else {
      resolved.object_id = 0
    }

    if (msg.object_frame !== undefined) {
      resolved.object_frame = geometry_msgs.msg.PoseStamped.Resolve(msg.object_frame)
    }
    else {
      resolved.object_frame = new geometry_msgs.msg.PoseStamped()
    }

    if (msg.desired_frame !== undefined) {
      resolved.desired_frame = geometry_msgs.msg.PoseStamped.Resolve(msg.desired_frame)
    }
    else {
      resolved.desired_frame = new geometry_msgs.msg.PoseStamped()
    }

    return resolved;
    }
};

module.exports = PartFetcherGoal;
