// Auto-generated. Do not edit!

// (in-package arm7dof_traj_as.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class trajResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.return_val = null;
    }
    else {
      if (initObj.hasOwnProperty('return_val')) {
        this.return_val = initObj.return_val
      }
      else {
        this.return_val = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type trajResult
    // Serialize message field [return_val]
    bufferOffset = _serializer.int32(obj.return_val, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type trajResult
    let len;
    let data = new trajResult(null);
    // Deserialize message field [return_val]
    data.return_val = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'arm7dof_traj_as/trajResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd272e5e4ccd8d235962127b04bb0773f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    #return_val = 1 for traj complete; traj_id should echo the input traj_id
    int32 return_val
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new trajResult(null);
    if (msg.return_val !== undefined) {
      resolved.return_val = msg.return_val;
    }
    else {
      resolved.return_val = 0
    }

    return resolved;
    }
};

module.exports = trajResult;
