(cl:defpackage object_manipulation_properties-srv
  (:use )
  (:export
   "OBJECTMANIPULATIONQUERY"
   "<OBJECTMANIPULATIONQUERY-REQUEST>"
   "OBJECTMANIPULATIONQUERY-REQUEST"
   "<OBJECTMANIPULATIONQUERY-RESPONSE>"
   "OBJECTMANIPULATIONQUERY-RESPONSE"
  ))

