(cl:in-package object_manipulation_properties-srv)
(cl:export '(OBJECT_ID-VAL
          OBJECT_ID
          GRIPPER_ID-VAL
          GRIPPER_ID
          QUERY_CODE-VAL
          QUERY_CODE
          GRASP_OPTION-VAL
          GRASP_OPTION
          VALID_REPLY-VAL
          VALID_REPLY
          GRASP_STRATEGY_OPTIONS-VAL
          GRASP_STRATEGY_OPTIONS
          GRIPPER_POSE_OPTIONS-VAL
          GRIPPER_POSE_OPTIONS
          TOOL_ROTZ_MAX-VAL
          TOOL_ROTZ_MAX
          TOOL_ROTZ_MIN-VAL
          TOOL_ROTZ_MIN
          OBJECT_ROTZ_MAX-VAL
          OBJECT_ROTZ_MAX
          OBJECT_ROTZ_MIN-VAL
          OBJECT_ROTZ_MIN
          TOOL_DZ_MAX-VAL
          TOOL_DZ_MAX
          TOOL_DZ_MIN-VAL
          TOOL_DZ_MIN
          TOOL_DSLIDE_MAX-VAL
          TOOL_DSLIDE_MAX
          TOOL_DSLIDE_MIN-VAL
          TOOL_DSLIDE_MIN
))