(cl:defpackage coordinator-msg
  (:use )
  (:export
   "<MANIPTASKACTION>"
   "MANIPTASKACTION"
   "<MANIPTASKACTIONFEEDBACK>"
   "MANIPTASKACTIONFEEDBACK"
   "<MANIPTASKACTIONGOAL>"
   "MANIPTASKACTIONGOAL"
   "<MANIPTASKACTIONRESULT>"
   "MANIPTASKACTIONRESULT"
   "<MANIPTASKFEEDBACK>"
   "MANIPTASKFEEDBACK"
   "<MANIPTASKGOAL>"
   "MANIPTASKGOAL"
   "<MANIPTASKRESULT>"
   "MANIPTASKRESULT"
  ))

